### ISSUE TITLE
提交网站：等疾风

### ISSUE THREAD

**Issue by Codesire-Deng** [pipecraft-net/nav#3]
## 提交网站

- 网站名称（必填）: 等疾风

- 网站网址（必填）: https://codesire-deng.github.io/

- 网站描述（必填）: 个人技术、算法分享，主力 C++ 

- LOGO URL（可选）:
  （也可以在这里上传图片）

- 网站标签（可选）: 程序员 C++

**Comment by PipecraftNet** [comment]
@Codesire-Deng 感谢关注本网站，并提交网站。
很抱歉，本导航站目前只收录以下几种网站类型。暂不收录个人博客网站。
- [垂直社区网站](https://zh.pipecraft.net/communities/)
- [垂直网址导航网站](https://zh.pipecraft.net/nav-sites/)
- [在线工具网站](https://zh.pipecraft.net/tools/)
- [个人独立博客聚合网站](https://zh.pipecraft.net/blog-collections/)
